[package]
name = "music_evo"
version = "0.1.0"
edition = "2021"

[dependencies]
rodio = "0.15"
rand = "0.8"
hound = "3.4.0"
postgres = "0.19"
dotenv = "0.15"
serde_json = "1.0.136"
bytes = "1.6.0"
serde = { version = "1.0.210", features = ["derive"] }